[build]
  publish = "out"
  command = "npm run build-prod"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  SMTP_HOST = "smtp.hostname.com"
  SMTP_USERNAME = "smtp-user"
  SMTP_PASSWORD = "smtp-password"
  SMTP_SENDER_EMAIL = "contact@hostname.com"
